# -*- coding: utf-8 -*-
"""Bisection Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEiepk-8u8At7zFxRePWnyJG1PuYVKpU
"""

import numpy as np

def bisection_method(f, a, b, tol=1e-6, max_iter=100, print_table=True):

    if f(a) * f(b) >= 0:
        raise ValueError("f(a) and f(b) must have opposite signs.")

    history = []

    if print_table:
        print(f"\n{'Iteration':<10} {'a':<12} {'b':<12} {'c':<12} {'f(c)':<12}")
        print("-"*60)

    for i in range(1, max_iter + 1):

        c = (a + b) / 2
        fc = f(c)

        history.append([i, a, b, c, fc])

        if print_table:
            print(f"{i:<10} {a:<12.6f} {b:<12.6f} {c:<12.6f} {fc:<12.6f}")

        if abs(fc) < tol or abs(b - a)/2 < tol:
            print(f"\n✓ Converged to root: {c:.8f}")
            return c, i, True, history

        if f(a) * fc < 0:
            b = c
        else:
            a = c

    print(f"\n⚠ Did not converge within {max_iter} iterations")
    return c, max_iter, False, history


def main():
    expr = input("Enter f(x): ")

    def f(x):
        return eval(expr)

    a = float(input("Enter a: "))
    b = float(input("Enter b: "))
    bisection_method(f, a, b, print_table=True)


if __name__ == "__main__":
    main()