# -*- coding: utf-8 -*-
"""Newton Raphson Method .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEiepk-8u8At7zFxRePWnyJG1PuYVKpU
"""

import numpy as np

def newton_method(f, df, x0, tol=1e-6, max_iter=100, print_table=True):
    """
    Newton-Raphson Method: x_{n+1} = x_n - f(x_n)/f'(x_n)

    Parameters:
    f: function - equation f(x)=0
    df: function - derivative of f
    x0: float - initial guess
    tol: float - tolerance for convergence
    max_iter: int - maximum number of iterations
    print_table: bool - whether to print iteration table

    Returns:
    root: float - approximated root
    iterations: int - number of iterations performed
    converged: bool - whether method converged
    history: list - list of [iteration, x, f(x)] for each step
    """

    x_curr = x0
    history = [[0, x_curr, f(x_curr)]]

    if print_table:
        print(f"\n{'Iteration':<10} {'x_n':<15} {'f(x_n)':<15} {'Error':<15}")
        print("-"*55)
        print(f"{0:<10} {x_curr:<15.8f} {f(x_curr):<15.8f} {'-':<15}")

    for i in range(1, max_iter + 1):

        df_val = df(x_curr)

        if abs(df_val) < 1e-15:
            if print_table:
                print("⚠ Derivative near zero. Method stopped.")
            return x_curr, i, False, history

        x_next = x_curr - f(x_curr) / df_val
        error = abs(x_next - x_curr)

        history.append([i, x_next, f(x_next)])

        if print_table:
            print(f"{i:<10} {x_next:<15.8f} {f(x_next):<15.8f} {error:<15.8f}")

        if error < tol or abs(f(x_next)) < tol:
            if print_table:
                print(f"\n✓ Converged to root: {x_next:.10f}")
                print(f"  Iterations: {i}")
                print(f"  f(root) = {f(x_next):.2e}")
            return x_next, i, True, history

        x_curr = x_next

    if print_table:
        print(f"\n⚠ Did not converge within {max_iter} iterations")

    return x_curr, max_iter, False, history


def main():
    expr = input("Enter f(x): ")
    dexpr = input("Enter f'(x): ")

    def f(x):
        return eval(expr)

    def df(x):
        return eval(dexpr)

    x0 = float(input("Enter initial guess x0: "))
    newton_method(f, df, x0, print_table=True)


if __name__ == "__main__":
    main()