# -*- coding: utf-8 -*-
"""Non linear systems (Newton Raphson Method).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdxH8kV_PnU655txXsYVQ4RXE2_CkyGX
"""

import numpy as np
from math import sin, cos, exp, pi

def newton_raphson_system(F, J, x0, tol=1e-6, max_iter=50):
    x = np.array(x0, dtype=float)

    for i in range(max_iter):
        Fx = np.array(F(x))
        Jx = np.array(J(x))

        try:
            delta = np.linalg.solve(Jx, -Fx)
        except np.linalg.LinAlgError:
            print("Jacobian is singular")
            return None

        x_new = x + delta

        print(f"Iteration {i+1}: {x_new}")

        if np.linalg.norm(delta) < tol:
            print("Converged")
            return x_new

        x = x_new

    print("No convergence")
    return None


n = int(input("Enter system size (2 or 3): "))

print("\nEnter initial values:")

if n == 2:
    x0 = [
        float(input("x0 = ")),
        float(input("y0 = "))
    ]
else:
    x0 = [
        float(input("x0 = ")),
        float(input("y0 = ")),
        float(input("z0 = "))
    ]


print("\nEnter equations using x, y, z:")

f1 = input("f1 = ")
f2 = input("f2 = ")
f3 = input("f3 = ") if n == 3 else None


print("\nEnter Jacobian values:")

j11 = input("df1/dx = ")
j12 = input("df1/dy = ")
j13 = input("df1/dz = ") if n == 3 else None

j21 = input("df2/dx = ")
j22 = input("df2/dy = ")
j23 = input("df2/dz = ") if n == 3 else None

if n == 3:
    j31 = input("df3/dx = ")
    j32 = input("df3/dy = ")
    j33 = input("df3/dz = ")


def F(v):
    x, y = v[0], v[1]

    if n == 2:
        return [
            eval(f1),
            eval(f2)
        ]
    else:
        z = v[2]
        return [
            eval(f1),
            eval(f2),
            eval(f3)
        ]


def J(v):
    x, y = v[0], v[1]

    if n == 2:
        return [
            [eval(j11), eval(j12)],
            [eval(j21), eval(j22)]
        ]
    else:
        z = v[2]
        return [
            [eval(j11), eval(j12), eval(j13)],
            [eval(j21), eval(j22), eval(j23)],
            [eval(j31), eval(j32), eval(j33)]
        ]


solution = newton_raphson_system(F, J, x0)

print("\nFinal Solution:", solution)